# prefix for all requests
server.contextPath: /v1

spring:
    jpa:
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: true
                format_sql: true
---
spring:
    profiles: utc
    jpa:
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
---
spring:
    profiles: default

    datasource:
        # serverTimezone affects rs.getTimestamp() without the Calendar argument:
        url: jdbc:mysql://localhost:3306/shakeitup
        username: shakeitup
        password: shakeitup
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate.ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect